behaviors: 
  CoinPicker: 
    behavioral_cloning: 
      demo_path: "E:\\RLUnity\\NewNewMl\\Assets\\Demonstrations\\CoinPicker.demo"
    hyperparameters: 
      batch_size: 10
      beta: 0.0005
      buffer_size: 100
      epsilon: 0.2
      lambd: 0.99
      learning_rate: 0.0003
      learning_rate_schedule: linear
      num_epoch: 3
    max_steps: 500000
    network_settings: 
      hidden_units: 128
      normalize: false
      num_layers: 2
    reward_signals: 
      extrinsic: 
        gamma: 0.99
        strength: 1.0
    summary_freq: 10000
    time_horizon: 64
    trainer_type: ppo